### ISSUE TITLE
CSV debugging is not working

### ISSUE THREAD

**Issue by admirkrilasevic** [the-wrench-io/hdes#35]
When attempting to debug a flow and define input data as CSV, the output is an execution error.
Inspecting the issue it was realized that CSVs are properly mapped (can be seen in developer tools console output), but the API call for debugging an asset (/assets/debugs) returns a 500 - Internal Server Error.

**Comment by olev-mutso** [comment]
2022-07-20 13:09:22.355 ERROR 1 --- [nio-8081-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Cannot build DebugResponse, some of required attributes are not set [id]] with root cause

java.lang.IllegalStateException: Cannot build DebugResponse, some of required attributes are not set [id]
	at io.resys.hdes.client.api.ImmutableDebugResponse$Builder.build(ImmutableDebugResponse.java:323)
	at io.resys.hdes.client.spi.composer.DebugVisitor.visit(DebugVisitor.java:57)
	at io.resys.hdes.client.spi.HdesComposerImpl.lambda$debug$11(HdesComposerImpl.java:118)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
